const descProjects = [
  {
    id: 1,
    name: "WildStone, Projet 2 en React et Tailwind",
    url: "https://wildstone.vercel.app/ ",
    image: "imgWildStone.png",
  },
  {
    id: 2,
    name: "Green My Mind, Hackathon en 30h React et SCSS",
    url: "https://green-my-mind.vercel.app/",
    image: "imgGreen.jpg",
  },
  {
    id: 3,
    name: "Personnage Animé, TJS",
    url: "https://react-tjs.vercel.app/",
    image: "imgAce.png",
  },
];

export default descProjects;
