const descProjects = [
  {
    id: 1,
    name: "WildStone, Projet 2 en React et Tailwind, durée 1 mois",
    url: "https://wildstone.vercel.app/ ",
    image: "wildStone.jpeg",
  },
  {
    id: 2,
    name: "Green My Mind, Hackathon en 30h React et SCSS",
    url: "https://green-my-mind.vercel.app/",
    image: "imgGreen.jpg",
  },
  {
    id: 3,
    name: "Personnage Animé, TJS",
    url: "https://react-tjs.vercel.app/",
    image: "imgAce.png",
  },
  {
    id: 4,
    name: "Site Florian Soria Photographe, React et Scss, durée 1 mois",
    url: "https://siteflo.vercel.app/",
    image: "imgFlo.jpg",
  },
];

export default descProjects;
