const descProjects = [
  {
    id: 1,
    name: "WildStone",
    url: "https://wildstone.vercel.app/ ",
    image: "imgWildStone.png",
  },
  {
    id: 2,
    name: "Green My Mind",
    url: "https://green-my-mind.vercel.app/",
    image: "imgGreen.jpg",
  },
  {
    id: 3,
    name: "Personnage Animé",
    url: "https://react-tjs.vercel.app/",
    image: "imgAce.png",
  },
];

export default descProjects;
